name: release

on:
  workflow_run:
    workflows: ["ci"]
    types:
      - completed

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-latest

    if: >
      github.event.workflow_run.conclusion == 'success' &&
      github.event.workflow_run.head_branch == 'main'

    steps:
      - name: Checkout
        uses: Nessiahs/nuxt-keycloak-oidc/.github/actions/checkout@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate changelog
        id: changelog
        uses: ./.github/actions/changelog
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit changelog
        if: steps.changelog.outputs.changelog != ''
        uses: ./.github/actions/commit
        env:
            VERSION: ${{ steps.changelog.outputs.changelog }}
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          message: "docs(changelog): update changelog [skip ci]"
          branch: docs/changelog-${{ env.VERSION }}

      - name: Create pr for changelog
        if: steps.changelog.outputs.changelog != ''
        id: pr
        env:
          VERSION: ${{ steps.changelog.outputs.changelog }}
        uses: ./.github/actions/pr
        with:
          base: "main"
          head: docs/changelog-${{ steps.changelog.outputs.changelog }}
          title: "docs(changelog): update changelog for version ${{ steps.changelog.outputs.changelog }}"
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Approve pr
        if: steps.changelog.outputs.changelog != '' && steps.pr.outputs.number != ''
        uses: ./.github/actions/approve-pr
        with:
          token: ${{ secrets.PAT_TOKEN }}
          number: ${{ steps.pr.outputs.number }}

      - name: merge pr
        if: steps.changelog.outputs.changelog != '' && steps.pr.outputs.number != ''
        uses: ./.github/actions/merge
        with:
          token: ${{ secrets.PAT_TOKEN }}
          number: ${{ steps.pr.outputs.number }}
